language: ruby
env:
  global:
    # BoxView API Key
    secure: "cOxF+9whdZHoCAxOPX0xiM7X312pRNoMaxHLDsBPaVLnk2kVKEURvJCoLqwhgsh9PVwa8wAXUk/cwUVN43isM3CdoMM4+5bZg18X/kQGM8zltKJCr/AONaBKV8gadVvmwdAsvzrQ/Mj4Qyb7AGJfNKjGPOZL8A0Pl1NypYz06lI="
rvm:
  - 2.0.0
  - 2.1.0
notifications:
  email:
    recipients:
      - vinny@getlua.com
    on_success: change
    on_failure: always
branches:
  only:
    - master